=== smartgrids-aau/Frevo/Components/IComponent.dtd
<!--
DTD for FREVO AbstractComponent
Version: Development 0.1
by Istvan Fehervari
-->

<!ELEMENT icomponent (config,properties,requirements*) >

<!ELEMENT config (entry)+ >

<!ELEMENT entry EMPTY >

<!ATTLIST entry
		key CDATA #REQUIRED
		type CDATA #REQUIRED
		value CDATA #REQUIRED >
		
<!ELEMENT properties (propentry*) >

<!ELEMENT propentry EMPTY >

<!ATTLIST propentry
		key CDATA #REQUIRED
		type CDATA #REQUIRED
		value CDATA #REQUIRED
		enumName CDATA #IMPLIED
		description CDATA #IMPLIED >
		
<!ELEMENT requirements (reqentry*) >

<!ELEMENT reqentry EMPTY >

<!ATTLIST reqentry
		key CDATA #REQUIRED
		type CDATA #REQUIRED
		value CDATA #REQUIRED >

=== smartgrids-aau/Frevo/Components/Problems/ddrones.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE zion SYSTEM "..//IComponent.dtd">

<icomponent>
	<config>
		<entry key="classdir" type="STRING"
			value="dDrones//components//ddrones" />
		<entry key="classname" type="STRING"
			value="components.ddrones.ddrones" />
		<entry key="name" type="STRING" value="dDrones" />
		<entry key="description" type="STRING"
			value="A discrete 2D simulated dDrones coverage scenario. Supports absolute fitness only." />
		<entry key="image" type="STRING" value="ddrones.png" />
		<entry key="tags" type="STRING" value="robots,drones" />
	</config>
	<properties>
		<propentry key="number_of_drones" type="INT" value="5" />
		<propentry key="cutofftime" type="INT" value="60000" />
		<propentry key="obstaclepercentage" type="INT" value="15" />
		<propentry key="evalnumber" type="INT" value="100" />
		<propentry key="gridwidth" type="INT" value="10" />
		<propentry key="gridheight" type="INT" value="10" />
		<propentry key="controller" type="ENUM"
			value="Evolved_cooperative_4_sensors"
			enumName="components.ddrones.ControllerModel"
			description="Defines the controller model. Can be evolved and static (for comparison)." />
	</properties>
	<requirements>
		<reqentry key="inputnumber" type="INT" value="4" />
		<reqentry key="outputnumber" type="INT" value="2" />
		<reqentry key="minimumCandidates" type="INT" value="1" />
		<reqentry key="maximumCandidates" type="INT" value="1" />
	</requirements>
</icomponent>

=== smartgrids-aau/Frevo/Components/Rankings/NoveltyRanking.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE frevo SYSTEM "..//IComponent.dtd">

<icomponent>
	<config>
		<entry key="classdir" type="STRING"
			value="NoveltyRanking/fehervari.noveltyranking" />
		<entry key="classname" type="STRING"
			value="fehervari.noveltyranking.NoveltyRanking" />
		<entry key="name" type="STRING" value="NoveltyRanking" />
		<entry key="description" type="STRING"
			value="Ranks candidates based on their novelty in the behavior space instead of fitness" />
		<entry key="image" type="STRING" value="NoveltyRanking.png" />
		<entry key="tags" type="STRING" value="absolute" />
	</config>
	<properties>
		<propentry key="initial_threshold" type="FLOAT" value="10f"
			description="Initial novelty threshold." />
	</properties>
</icomponent>

=== smartgrids-aau/Frevo/Components/Problems/InvertedPendulum.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE frevo SYSTEM "..//IComponent.dtd">

<icomponent>
	<config>
		<entry key="author" type="STRING"
			value="Thomas Dittrich, Wilfried Elmenreich" />
		<entry key="version" type="STRING" value="1.0" />
		<entry key="classdir" type="STRING"
			value="InvertedPendulum/InvertedPendulum" />
		<entry key="classname" type="STRING"
			value="InvertedPendulum.InvertedPendulum" />
		<entry key="name" type="STRING" value="InvertedPendulum" />
		<entry key="description" type="STRING"
			value="An inverted pendulum is a pendulum which has its mass above its pivot point. It is implemented with the pivot point mounted on a cart that can move horizontally. This problem is evaluating the controller of the cart with the task to keep the pendulum balanced over the simulation time." />
		<entry key="image" type="STRING" value="InvertedPendulum.png" />
		<entry key="tags" type="STRING" value="InvertedPendulum TAG" />
	</config>
	<properties>
		<propentry key="length_of_timestep_ms" type="FLOAT"
			value="1f"
			description="The length of one simulation step in milliseconds." />
		<propentry key="number_of_timesteps" type="INT"
			value="10000" description="Number of timesteps per simulation run." />
		<propentry key="fitnessmodel" type="ENUM"
			value="ANGLE_POW_2_PLUS_USED_WAY"
			enumName="InvertedPendulum.FitnessModel"
			description="Decides what factors shall be taking into account when evaluating a solution." />
		<propentry key="inputmodel" type="ENUM"
			value="ANGLE_VPENDULUM_VSLIDE" enumName="InvertedPendulum.InputModel"
			description="Sets what information shall be passed to the controller before each time step." />
	</properties>
	<requirements>
		<reqentry key="inputnumber" type="INT" value="4" />
		<reqentry key="outputnumber" type="INT" value="1" />
		<reqentry key="minimumCandidates" type="INT" value="1" />
		<reqentry key="maximumCandidates" type="INT" value="1" />
	</requirements>
</icomponent>

=== smartgrids-aau/Frevo/Components/Methods/CuckooSearch.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE frevo SYSTEM "..//IComponent.dtd">

<icomponent>
  <config>
    <entry key="classdir" type="STRING" value="CuckooSearch/frevo/cuckoosearch"/>
    <entry key="classname" type="STRING" value="frevo.cuckoosearch.CuckooSearch"/>
	<entry key="name" type="STRING" value="CuckooSearch"/>
	<entry key="description" type="STRING" value="Cuckoo search based on the work from Yang and Deb: &lt;a href=&quot;http://arxiv.org/pdf/1003.1594.pdf&quot;&gt;Cuckoo search via LÃ©vy flights&lt;/a&gt;"/>
	<entry key="image" type="STRING" value="cuckoosearch.png"/>
	<entry key="tags" type="STRING" value="CuckooSearch TAG"/>
  </config>
  <properties>
	<propentry key="number_of_nests" type="INT" value="50" description="Number of nests during the simulation."/>
	<propentry key="discovery_rate" type="FLOAT" value="0.25" description="Discovery rate of alien eggs."/>
	<propentry key="generations" type="INT" value="200" description="Number of generations."/>
  </properties>
</icomponent>

=== smartgrids-aau/Frevo/Components/Rankings/absoluteRanking.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE zion SYSTEM "..//IComponent.dtd">

<icomponent>
	<config>
		<entry key="author" type="STRING"
			value="Istvan Fehervari, Tobias Ibouning" />
		<entry key="version" type="STRING" value="1.1" />
		<entry key="classdir" type="STRING"
			value="AbsoluteRanking/AbsoluteRanking" />
		<entry key="classname" type="STRING"
			value="AbsoluteRanking.AbsoluteRanking" />
		<entry key="name" type="STRING" value="Absolute Rank" />
		<entry key="description" type="STRING"
			value="This algorithm eveluates each canditate separately and sorts the list according to the fitness scores. Uses multiple threads if the parameter 'parallelthreads' is set larger than 1." />
		<entry key="image" type="STRING" value="absoluteRanking.png" />
		<entry key="tags" type="STRING" value="absolute" />
	</config>
	<properties>
		<propentry key="parallelthreads" type="INT" value="1"
			description="Number of parallel threads that run the ranking." />
	</properties>
</icomponent>

=== smartgrids-aau/Frevo/Components/Problems/EvoPCO.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE frevo SYSTEM "..//IComponent.dtd">

<icomponent>
  <config>
    <entry key="classdir" type="STRING" value="EvoPCO/fehervari.evopco"/>
    <entry key="classname" type="STRING" value="fehervari.evopco.EvoPCO"/>
	<entry key="name" type="STRING" value="EvoPCO"/>
	<entry key="description" type="STRING" value="Simulates and evolves jumping policies of pulse-coupled oscillators with the JProwler simulator"/>
	<entry key="image" type="STRING" value="EvoPCO.png"/>
	<entry key="tags" type="STRING" value="EvoPCO TAG"/>
  </config>
  <properties>
	<propentry key="number_of_nodes" type="INT" value="5"/>
	<propentry key="number_of_evaluations" type="INT" value="1"/>
	<propentry key="simulation_length_s" type="INT" value="100"/>
	<propentry key="radio_model" type="ENUM" value="RAYLEIGH_RADIO_MODEL" enumName="fehervari.evopco.RadioModel"/>
	<propentry key="network_topology" type="ENUM" value="REGULAR_GRID_TOPOLOGY" enumName="fehervari.evopco.NetworkTopology"/>
	<propentry key="jumping_policy" type="ENUM" value="FIREFLY_POLICY" enumName="fehervari.evopco.JumpingPolicy"/>
	<propentry key="area_side_length_m" type="FLOAT" value="100f"/>
	<propentry key="clock_drift" type="INT" value="0"/>
	<propentry key="random_false_positive" type="FLOAT" value="0.01f"/>
  </properties>
  <requirements>
    <reqentry key="inputnumber" type="INT" value="1"/>
    <reqentry key="outputnumber" type="INT" value="1"/>
    <reqentry key="minimumCandidates" type="INT" value="1"/>
    <reqentry key="maximumCandidates" type="INT" value="1"/>
  </requirements>
</icomponent>

=== smartgrids-aau/Frevo/Components/Problems/RobotSoccer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE frevo SYSTEM "..//IComponent.dtd">

<icomponent>
  <config>
	<entry key="author" type="STRING" value="Istvan Fehervari, Hinrich Arnoldt"/>
	<entry key="version" type="STRING" value="1.00"/>
    <entry key="classdir" type="STRING" value="RobotSoccer/fehervari.robotsoccer"/>
    <entry key="classname" type="STRING" value="fehervari.robotsoccer.RobotSoccer"/>
	<entry key="name" type="STRING" value="RobotSoccer"/>
	<entry key="description" type="STRING" value="A simulated robot soccer using autonomous mobile robots."/>
	<entry key="image" type="STRING" value="RobotSoccer.png"/>
	<entry key="tags" type="STRING" value="RobotSoccer TAG"/>
	<entry key="support_heterogeneity" type="BOOLEAN" value="true"/>
  </config>
  <properties>
	<propentry key="playersPerTeam" type="INT" value="11" description="Number of players per team."/>
	<propentry key="evaluation_time" type="INT" value="60" description="Defines the length of the game in seconds."/>
	<propentry key="simulation_steps_per_second" type="INT" value="10" description="Number of timesteps calculated each real-time second."/>
  </properties>
  <requirements>
    <reqentry key="inputnumber" type="INT" value="15"/>
    <reqentry key="outputnumber" type="INT" value="4"/>
    <reqentry key="minimumCandidates" type="INT" value="2"/>
    <reqentry key="maximumCandidates" type="INT" value="2"/>
  </requirements>
</icomponent>

=== smartgrids-aau/Frevo/Components/Representations/threeLayeredNetwork.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE zion SYSTEM "..//IComponent.dtd">

<icomponent>
	<config>
		<entry key="author" type="STRING"
			value="Istvan Fehervari, Wilfried Elmenreich" />
		<entry key="version" type="STRING" value="1.00" />
		<entry key="classdir" type="STRING"
			value="LayeredNetwork/threeLayerNetwork" />
		<entry key="classname" type="STRING"
			value="threeLayerNetwork.ThreeLayerNetwork" />
		<entry key="name" type="STRING"
			value="Three layered neural network" />
		<entry key="description" type="STRING"
			value="Feed-forward, non-recurrent artificial neural network with one hidden layer. Only weights and biases will change during evolution." />
		<entry key="image" type="STRING" value="layerednetwork.png" />
		<entry key="tags" type="STRING" value="neural network" />
	</config>
	<properties>
		<propentry key="hiddenNodes" type="INT" value="2"
			description="Number of neurons in the hidden layer." />
		<propentry key="weight_range" type="FLOAT" value="2f"
			description="Range of the inital randomly created weights." />
		<propentry key="bias_range" type="FLOAT" value="2f"
			description="Range of the inital randomly created biases." />
		<propentry key="stepNumber" type="INT" value="2"
			description="Number of times the whole network is executed before returning its output." />
	</properties>
</icomponent>
