=== smartgrids-aau/Frevo/Components/IComponent.dtd
<!--
DTD for FREVO AbstractComponent
Version: Development 0.1
by Istvan Fehervari
-->

<!ELEMENT icomponent (config,properties,requirements*) >

<!ELEMENT config (entry)+ >

<!ELEMENT entry EMPTY >

<!ATTLIST entry
		key CDATA #REQUIRED
		type CDATA #REQUIRED
		value CDATA #REQUIRED >
		
<!ELEMENT properties (propentry*) >

<!ELEMENT propentry EMPTY >

<!ATTLIST propentry
		key CDATA #REQUIRED
		type CDATA #REQUIRED
		value CDATA #REQUIRED
		enumName CDATA #IMPLIED
		description CDATA #IMPLIED >
		
<!ELEMENT requirements (reqentry*) >

<!ELEMENT reqentry EMPTY >

<!ATTLIST reqentry
		key CDATA #REQUIRED
		type CDATA #REQUIRED
		value CDATA #REQUIRED >

=== smartgrids-aau/Frevo/Components/Problems/Max_Traveler.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE frevo SYSTEM "..//IComponent.dtd">

<icomponent>
  <config>
    <entry key="classdir" type="STRING" value="Max_Traveler/Max_Traveler"/>
    <entry key="classname" type="STRING" value="Max_Traveler.Max_Traveler"/>
	<entry key="name" type="STRING" value="Max_Traveler"/>
	<entry key="description" type="STRING" value="This is a simulation where seven Robots are in a quadratic arena and try to drive as far as possible without
hitting an obstacle"/>
	<entry key="image" type="STRING" value="Max_Traveler.png"/>
	<entry key="tags" type="STRING" value="Max_Traveler TAG"/>
  </config>
  <properties>
	<propentry key="numSteps" type="INT" value="500"/>
	<propentry key="serverAddress" type="STRING" value="127.0.0.1"/>
  </properties>
  <requirements>
    <reqentry key="inputnumber" type="INT" value="24"/>
    <reqentry key="outputnumber" type="INT" value="2"/>
    <reqentry key="minimumCandidates" type="INT" value="1"/>
    <reqentry key="maximumCandidates" type="INT" value="1"/>
  </requirements>
</icomponent>

=== smartgrids-aau/Frevo/Components/Problems/ttt3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE zion SYSTEM "..//IComponent.dtd">

<icomponent>
  <config>
    <entry key="classdir" type="STRING" value="ttt3/ttt3"/>
    <entry key="classname" type="STRING" value="ttt3.ttt3"/>
	<entry key="name" type="STRING" value="Tic Tac Toe 3x3"/>
	<entry key="description" type="STRING" value="A game for two players, blue and red, who take turns marking the spaces in a 3x3 grid, usually red going first. The player who succeeds in placing three respective marks in a horizontal, vertical or diagonal row wins the game."/>
	<entry key="image" type="STRING" value="ttt3.png"/>
	<entry key="tags" type="STRING" value="game"/>
  </config>
  <properties>
  </properties>
  <requirements>
    <reqentry key="inputnumber" type="INT" value="9"/>
	<reqentry key="outputnumber" type="INT" value="9"/>
	<reqentry key="minimumCandidates" type="INT" value="2"/>
    <reqentry key="maximumCandidates" type="INT" value="2"/>
  </requirements>
</icomponent>

=== smartgrids-aau/Frevo/Components/Representations/multiLayeredNetwork.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE frevo SYSTEM "..//IComponent.dtd">

<icomponent>
  <config>
    <entry key="classdir" type="STRING" value="LayeredNetwork/multiLayerNetwork"/>
    <entry key="classname" type="STRING" value="multiLayerNetwork.MultiLayerNetwork"/>
	<entry key="name" type="STRING" value="Multi layered neural network"/>
	<entry key="description" type="STRING" value="Feed-forward neural network with multiple hidden layers. Extension of three layered neural network"/>
	<entry key="image" type="STRING" value="Multi layered neural network.png"/>
	<entry key="tags" type="STRING" value="Multi layered neural network TAG"/>
  </config>
  <properties>
	<propentry key="hidden_layers" type="INT" value="2"
		description="Number of hidden layers." />
		<propentry key="nodes_per_layer" type="INT" value="2"
		description="Number of neurons per hidden layer." />
	<propentry key="weight_range" type="FLOAT" value="2f"
		description="Range of the inital randomly created weights." />
	<propentry key="bias_range" type="FLOAT" value="2f"
		description="Range of the inital randomly created biases." />
	<propentry key="stepNumber" type="INT" value="1"
		description="Number of times the whole network is executed before returning its output." />
  </properties>
</icomponent>

=== smartgrids-aau/Frevo/Components/Problems/cdrones.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE frevo SYSTEM "..//IComponent.dtd">

<icomponent>
	<config>
		<entry key="classdir" type="STRING"
			value="cDrones//components//cdrones" />
		<entry key="classname" type="STRING"
			value="components.cdrones.cdrones" />
		<entry key="name" type="STRING" value="cDrones" />
		<entry key="description" type="STRING"
			value="A 2D simulated cDrones coverage scenario. Supports absolute fitness only." />
		<entry key="image" type="STRING" value="cdrones.png" />
		<entry key="tags" type="STRING" value="robots,drones" />
	</config>
	<properties>
		<propentry key="number_of_drones" type="INT" value="5" />
		<propentry key="cutofftime" type="INT" value="60000" />
		<propentry key="obstaclepercentage" type="FLOAT"
			value="0.15f" />
		<propentry key="evalnumber" type="INT" value="100" />
		<propentry key="numberofrandominputs" type="INT" value="0" />
		<propentry key="randomstart" type="BOOLEAN" value="false" />
		<propentry key="commFitness" type="BOOLEAN" value="false" />
		<propentry key="basestep" type="INT" value="10" />
		<propentry key="ControllerType" type="ENUM"
			value="RANDOMWALKCONTROLLER"
			enumName="components.cdrones.ControllerType" />
		<propentry key="fieldWidthX" type="INT" value="200" />
		<propentry key="fieldWidthY" type="INT" value="160" />
		<propentry key="resolution" type="INT" value="10" />
		<propentry key="commFitness" type="BOOLEAN" value="false" />
		<propentry key="numberofdigits" type="INT" value="2" />
	</properties>
	<requirements>
		<reqentry key="inputnumber" type="INT" value="8" />
		<reqentry key="outputnumber" type="INT" value="2" />
		<reqentry key="minimumCandidates" type="INT" value="1" />
		<reqentry key="maximumCandidates" type="INT" value="1" />
	</requirements>
</icomponent>

=== smartgrids-aau/Frevo/Components/Representations/NEAT.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE zion SYSTEM "..//IComponent.dtd">

<icomponent>
	<config>
		<entry key="classdir" type="STRING" value="NEAT//neat" />
		<entry key="classname" type="STRING" value="neat.NEAT" />
		<entry key="name" type="STRING" value="NEAT" />
		<entry key="description" type="STRING"
			value="Neuroevolution of augmenting topologies" />
		<entry key="image" type="STRING" value="NEAT.png" />
		<entry key="tags" type="STRING" value="NEAT TAG" />
	</config>
	<properties>
		<propentry key="disjoint_coeff" type="FLOAT" value="1f" />
		<propentry key="excess_coeff" type="FLOAT" value="1f" />
		<propentry key="weight_coeff" type="FLOAT" value="0.4f" />
		<propentry key="recursive" type="BOOLEAN" value="false" />
		<propentry key="feature_selection" type="BOOLEAN"
			value="false" />
		<propentry key="max_perturbation" type="FLOAT" value="0.5f" />
		<propentry key="max_bias_perturbation" type="FLOAT"
			value="0.1f" />

		<propentry key="add_node_prob" type="FLOAT" value="0.005f" />
		<propentry key="add_link_prob" type="FLOAT" value="0.10f" />
		<propentry key="mutate_node_weight_replaced_prob"
			type="FLOAT" value="0.001f" />
		<propentry key="mutate_link_toggle_prob" type="FLOAT"
			value="0.1f" />
		<propentry key="mutate_node_sf_prob" type="FLOAT"
			value="0.1f" />
		<propentry key="mutate_feature_prob" type="FLOAT"
			value="0.1f" />
		<propentry key="mutate_node_bias_prob" type="FLOAT"
			value="0.1f" />
		<propentry key="mutate_link_weight_prob" type="FLOAT"
			value="0.6f" />
	</properties>
</icomponent>

=== smartgrids-aau/Frevo/Components/Problems/simplesoccer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE zion SYSTEM "..//IComponent.dtd">

<icomponent>
	<config>
		<entry key="author" type="STRING" value="Istvan Fehervari" />
		<entry key="version" type="STRING" value="1.00" />
		<entry key="classdir" type="STRING"
			value="SimpleSoccer/components/simplesoccer" />
		<entry key="classname" type="STRING"
			value="components.simplesoccer.SimpleSoccer" />
		<entry key="name" type="STRING" value="Simplified Robot Soccer" />
		<entry key="description" type="STRING"
			value="A 2D simulated simplfied robot soccer game. Fitness is evaluated based on a weighted sum. Each player is controlled by an own controller instantiated from the same candidate representation. Thus, the game is a product of a self-organized process. The players receive very limited information on the ongoing game, such as the distance to the ball, the distance to the closest teammate/opponent and some information about the borders.
	Supports 1v1 ranking systems. Does not support absolute fitness." />
		<entry key="image" type="STRING" value="simplesoccer.png" />
		<entry key="tags" type="STRING" value="game,robots" />
	</config>
	<properties>
		<propentry key="playersPerTeam" type="INT" value="10"
			description="The number of players per team." />
		<propentry key="position_weight" type="INT" value="1"
			description="Weight value of the fitness objective measuring the distribution on the team on the field" />
		<propentry key="ball_distance_weight" type="INT"
			value="1000"
			description="Weight value of the fitness objective measuring the distance between the players and the ball." />
		<propentry key="kick_weight" type="INT" value="20000"
			description="Weight value of the fitness objective measuring the importance of kicking." />
		<propentry key="ball_goal_weight" type="INT" value="100000"
			description="Weight value of the fitness objective measuring the distance of the ball to the opponent's goal." />
		<propentry key="score_weight" type="INT" value="4000000"
			description="Weight value of the fitness objective measuring the importance of scoring a goal." />
		<propentry key="evaluation_time" type="INT" value="60000"
			description="Defines the length of the game in miliseconds." />
		<propentry key="isCartesian_interpretation" type="BOOLEAN"
			value="TRUE"
			description="If true, all information to the controllers will be passed as caresian coordinates instead of polar." />
		<propentry key="max_kicks" type="INT" value="10"
			description="The maximum number of kicks per team which we take in account to calculate a fitness." />
		<propentry key="apply_stamina_model" type="BOOLEAN"
			value="FALSE"
			description="Apply stamina model for the player in the soccer simulation." />
		<propentry key="controller_model" type="ENUM"
			value="NEARESTINFOPLAYER"
			enumName="components.simplesoccer.PlayerModel"
			description="Player controller model" />
	</properties>
	<requirements>
		<reqentry key="inputnumber" type="INT" value="16" />
		<reqentry key="outputnumber" type="INT" value="4" />
		<reqentry key="minimumCandidates" type="INT" value="2" />
		<reqentry key="maximumCandidates" type="INT" value="2" />
	</requirements>
</icomponent>

=== smartgrids-aau/Frevo/Components/Methods/NoveltySearch.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE frevo SYSTEM "..//IComponent.dtd">

<icomponent>
	<config>
		<entry key="classdir" type="STRING"
			value="NoveltySearch/fehervari/noveltysearch" />
		<entry key="classname" type="STRING"
			value="fehervari.noveltysearch.NoveltySearch" />
		<entry key="name" type="STRING" value="NoveltySearch" />
		<entry key="description" type="STRING"
			value="Novelty search based on the implementation of Lehman and Stanley. This method ignores the selected ranking component." />
		<entry key="image" type="STRING" value="NoveltySearch.png" />
		<entry key="tags" type="STRING" value="NoveltySearch TAG" />
	</config>
	<properties>
		<propentry key="populationsize" type="INT" value="100"
			description="Size of the population." />
		<propentry key="generations" type="INT" value="200"
			description="Number of generations." />
		<propentry key="initial_novelty_threshold" type="FLOAT"
			value="6.0f" description="The initial novelty threshold." />
		<propentry key="mutate_only_probablity" type="FLOAT"
			value="0.3f"
			description="Chance that only a mutation occurs instead of a crossover." />
		<propentry key="mutation_severity" type="FLOAT" value="0.3f"
			description="Severity of the mutations during evolution." />
		<propentry key="mutation_method" type="INT" value="1"
			description="The index of the default mutation method to be used." />
	</properties>
</icomponent>

=== smartgrids-aau/Frevo/Components/Methods/gaspecies.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE zion SYSTEM "..//IComponent.dtd">

<icomponent>
	<config>
		<entry key="classdir" type="STRING" value="gaspecies/gaspecies" />
		<entry key="classname" type="STRING" value="gaspecies.GASpecies" />
		<entry key="name" type="STRING" value="GASpecies" />
		<entry key="description" type="STRING"
			value="Evolutionary method which classifies candidates into species and uses explicit fitness sharing. Works best with absolute fitness." />
		<entry key="image" type="STRING" value="GASpecies.png" />
		<entry key="tags" type="STRING" value="Species" />
	</config>
	<properties>
		<propentry key="populationsize" type="INT" value="50"
			description="Size of a population." />
		<propentry key="initial_compatibility_threshold"
			type="FLOAT" value="0.5"
			description="The initial compatibility threshold that determines the genetic closeness of two candidates." />
		<propentry key="time_alive_minimum" type="INT" value="0"
			description="Minimum time for being mature for selection or death in a specie." />
		<propentry key="generations" type="INT" value="200"
			description="Number of generations." />
		<propentry key="save_interval" type="INT" value="0"
			description="Number of generations between each save. Zero turns off regular saving." />
		<propentry key="survival_threshold" type="FLOAT" value="0.4"
			description="Factor for calculating the number of surviving offsprings." />

		<propentry key="mutate_only_probablity" type="FLOAT"
			value="0.3f"
			description="Chance that only a mutation occurs instead of a crossover." />
		<propentry key="interspecies_mate_rate" type="FLOAT"
			value="0.001f"
			description="Chance that mating happens only within species." />
		<propentry key="mate_only_prob" type="FLOAT" value="0.2"
			description="Chance that only mutation occurs" />
	</properties>
</icomponent>
