=== smartgrids-aau/Frevo/Components/IComponent.dtd
<!--
DTD for FREVO AbstractComponent
Version: Development 0.1
by Istvan Fehervari
-->

<!ELEMENT icomponent (config,properties,requirements*) >

<!ELEMENT config (entry)+ >

<!ELEMENT entry EMPTY >

<!ATTLIST entry
		key CDATA #REQUIRED
		type CDATA #REQUIRED
		value CDATA #REQUIRED >
		
<!ELEMENT properties (propentry*) >

<!ELEMENT propentry EMPTY >

<!ATTLIST propentry
		key CDATA #REQUIRED
		type CDATA #REQUIRED
		value CDATA #REQUIRED
		enumName CDATA #IMPLIED
		description CDATA #IMPLIED >
		
<!ELEMENT requirements (reqentry*) >

<!ELEMENT reqentry EMPTY >

<!ATTLIST reqentry
		key CDATA #REQUIRED
		type CDATA #REQUIRED
		value CDATA #REQUIRED >

=== smartgrids-aau/Frevo/Components/Problems/SmartGrid.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE zion SYSTEM "..//IComponent.dtd">

<icomponent>
  <config>
    <entry key="classdir" type="STRING" value="SmartGrid/sg"/>
    <entry key="classname" type="STRING" value="sg.SmartGrid"/>
	<entry key="name" type="STRING" value="SmartGrid"/>
	<entry key="description" type="STRING" value="Simple Example to show the functions of frevo"/>
	<entry key="image" type="STRING" value="SmartGrid.png"/>
	<entry key="tags" type="STRING" value="SmartGrid TAG"/>
  </config>
  <properties>
  		<propentry key="numberOfHouses" type="INT" value="10"/>
  		<propentry key="neededEnergy" type="INT" value="5600"/>
  		<propentry key="penalty" type="INT" value="3"/>
  </properties>
  <requirements>
    <reqentry key="inputnumber" type="INT" value="7"/>
    <reqentry key="outputnumber" type="INT" value="1"/>
    <reqentry key="minimumCandidates" type="INT" value="1"/>
    <reqentry key="maximumCandidates" type="INT" value="1"/>
  </requirements>
</icomponent>

=== smartgrids-aau/Frevo/Components/Problems/cam.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE frevo SYSTEM "..//IComponent.dtd">

<icomponent>
	<config>
		<entry key="author" type="STRING"
			value="Istvan Fehervari, Wilfried Elmenreich" />
		<entry key="version" type="STRING" value="1.13a" />
		<entry key="classdir" type="STRING" value="CAM/cam" />
		<entry key="classname" type="STRING" value="cam.Cam" />
		<entry key="name" type="STRING" value="Cam" />
		<entry key="description" type="STRING"
			value="Cellular automaton morphogenesis. A cellular automaton whose control is evolved by the system. The fitness is determined by the state after several simulation steps.&lt;br&gt;&lt;br&gt;If the parameter &lt;i&gt;bestsolutionOutOfNSteps&lt;/i&gt; is enabled, the best solution within the defined fitness steps defines the fitness.&lt;br&gt;&lt;br&gt;Otherwise, the parameter &lt;i&gt;fitness_steps&lt;/i&gt; determines, how many system states are taken into account for the fitness evaluation, thus forcing to evolve a more stable solution.&lt;br&gt;The &lt;i&gt;smartFitnessModel&lt;/i&gt; defines if pixels on edges are getting more weight." />
		<entry key="image" type="STRING" value="cam.png" />
		<entry key="tags" type="STRING" value="cellular automata" />
	</config>
	<properties>
		<propentry key="inputmodel" type="ENUM"
			value="COLOR_OUTPUT_V_NEUMANN" enumName="cam.InputModel"
			description="Sets what type of inputs should a cell receive each timestep. Moore and Von Neumann neighborhoods are considered." />
		<propentry key="bestsolutionOutOfNSteps" type="BOOLEAN"
			value="false" />
		<propentry key="smartFitnessModel" type="BOOLEAN"
			value="true" />
		<propentry key="simulation_steps" type="INT" value="20" />
		<propentry key="fitness_steps" type="INT" value="1" />
		<propentry key="picture" type="FILE"
			value="Components\Problems\CAM\austria-flag 6x9.png" />
		<propentry key="istorroid" type="BOOLEAN" value="false" />
		<propentry key="1-of-C" type="BOOLEAN" value="false" />
	</properties>
	<requirements>
		<reqentry key="inputnumber" type="INT" value="8" />
		<reqentry key="outputnumber" type="INT" value="5" />
		<reqentry key="minimumCandidates" type="INT" value="1" />
		<reqentry key="maximumCandidates" type="INT" value="1" />
	</requirements>
</icomponent>

=== smartgrids-aau/Frevo/Components/Problems/XOR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE zion SYSTEM "..//IComponent.dtd">

<icomponent>
	<config>
		<entry key="author" type="STRING" value="Istvan Fehervari" />
		<entry key="version" type="STRING" value="1.00" />
		<entry key="classdir" type="STRING" value="XOR/XOR" />
		<entry key="classname" type="STRING" value="XOR.XOR" />
		<entry key="name" type="STRING" value="XOR" />
		<entry key="description" type="STRING"
			value="A simple XOR problem to test evolutionary algorithms if they work properly. Fitness is determined by the mean square error." />
		<entry key="image" type="STRING" value="xor.png" />
		<entry key="tags" type="STRING" value="XOR TAG" />
	</config>
	<properties>
	</properties>
	<requirements>
		<reqentry key="inputnumber" type="INT" value="2" />
		<reqentry key="outputnumber" type="INT" value="1" />
		<reqentry key="minimumCandidates" type="INT" value="1" />
		<reqentry key="maximumCandidates" type="INT" value="1" />
	</requirements>
</icomponent>

=== smartgrids-aau/Frevo/Components/Problems/Pong.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE frevo SYSTEM "..//IComponent.dtd">

<icomponent>
	<config>
		<entry key="author" type="STRING" value="Sergii Zhevzhyk" />
		<entry key="version" type="STRING" value="1.00" />
		<entry key="classdir" type="STRING" value="pong/Pong" />
		<entry key="classname" type="STRING" value="pong.Pong" />
		<entry key="name" type="STRING" value="Pong" />
		<entry key="description" type="STRING" value="Pong game" />
		<entry key="image" type="STRING" value="pong.png" />
		<entry key="tags" type="STRING" value="pong game" />
	</config>
	<properties>
		<!-- concerning the paddles -->
		<propentry key="playersPerTeam" type="INT" value="3"
			description="Number of players (paddles) per team." />
		<propentry key="paddleHeight" type="INT" value="60"
			description="The height of the paddle." />
		<propentry key="paddleSpeed" type="FLOAT" value="4"
			description="Maximum speed of the paddle." />

		<!-- concerning the ball -->
		<propentry key="numberOfBalls" type="INT" value="1"
			description="The number of balls in game." />

		<!-- simulation -->
		<propentry key="maximumSteps" type="INT" value="2000"
			description="Number of steps in simulation" />
	</properties>
	<requirements>
		<reqentry key="inputnumber" type="INT" value="3" />
		<reqentry key="outputnumber" type="INT" value="1" />
		<reqentry key="minimumCandidates" type="INT" value="2" />
		<reqentry key="maximumCandidates" type="INT" value="2" />
	</requirements>
</icomponent>

=== smartgrids-aau/Frevo/Components/Methods/PSO.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE zion SYSTEM "..//IComponent.dtd">

<icomponent>
  <config>
    <entry key="author" type="STRING" value="Sergii Zhevzhyk"/>
	<entry key="version" type="STRING" value="1.00"/>
    <entry key="classdir" type="STRING" value="PSO/PSO"/>
    <entry key="classname" type="STRING" value="pso.PSO"/>
	<entry key="name" type="STRING" value="PSO"/>
	<entry key="description" type="STRING" value="Particle Swarm Optimization(PSO).  PSO is originally attributed to Kennedy, Eberhart and Shi"></entry>
	<entry key="image" type="STRING" value="PSO.png"/>
	<entry key="tags" type="STRING" value="PSO particle swarm"/>
  </config>
  <properties>
      <propentry key="generations" type="INT" value="200" description="Number of generations." />
      <propentry key="populationsize" type="INT" value="100" description="Size of a population."/>
      <propentry key="W" type="FLOAT" value="0.7f" description="Inertia weight"/>
      <propentry key="C1" type="FLOAT" value="2.4f" description="Cognitive learning rate or tendency to return to personal best position. Should be positive number"/>
      <propentry key="C2" type="FLOAT" value="2.1f" description="Social learning rate or tendency to move towards the swarm best position. Should be positive number"/>
  </properties>
</icomponent>

=== smartgrids-aau/Frevo/Components/Problems/Spiderino.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE frevo SYSTEM "..//IComponent.dtd">

<icomponent>
  <config>
    <entry key="classdir" type="STRING" value="spiderino/Spiderino"/>
    <entry key="classname" type="STRING" value="spiderino.Spiderino"/>
	<entry key="name" type="STRING" value="Spiderino"/>
	<entry key="description" type="STRING" value="Simulation of the Spiderino Swarm bots looking for a light source."/>
	<entry key="image" type="STRING" value="spiderino.png"/>
	<entry key="tags" type="STRING" value="spiderino TAG"/>
  </config>
  <properties>
	<!-- Place your properties here -->
  </properties>
  <requirements>
    <reqentry key="inputnumber" type="INT" value="12"/>
    <reqentry key="outputnumber" type="INT" value="2"/>
    <reqentry key="minimumCandidates" type="INT" value="1"/>
    <reqentry key="maximumCandidates" type="INT" value="1"/>
  </requirements>
</icomponent>

=== smartgrids-aau/Frevo/Components/Problems/patterns.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE zion SYSTEM "..//IComponent.dtd">

<icomponent>
  <config>
    <entry key="classdir" type="STRING" value="Patterns/patterns"/>
    <entry key="classname" type="STRING" value="patterns.Patterns"/>
	<entry key="name" type="STRING" value="Patterns"/>
	<entry key="description" type="STRING" value="A test problem to learn and predict a given sequence of digits"/>
	<entry key="image" type="STRING" value="patterns.png"/>
	<entry key="tags" type="STRING" value="numbers"/>
  </config>
  <properties>
	<propentry key="numberofdigits" type="INT" value="8"/>
	<propentry key="numberofteaching" type="INT" value="3"/>
	<propentry key="numbersystem" type="INT" value="10"/>	
	<propentry key="numberoftrainingpatterns" type="INT" value="100"/>	
  </properties>
  <requirements>
    <reqentry key="inputnumber" type="INT" value="1"/>
    <reqentry key="outputnumber" type="INT" value="1"/>
    <reqentry key="minimumCandidates" type="INT" value="1"/>
    <reqentry key="maximumCandidates" type="INT" value="1"/>
  </requirements>
</icomponent>

=== smartgrids-aau/Frevo/Components/Problems/NodeManager.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE zion SYSTEM "..//IComponent.dtd">

<icomponent>
  <config>
    <entry key="classdir" type="STRING" value="querySched"/>
    <entry key="classname" type="STRING" value="sched.NodeManager"/>
	<entry key="name" type="STRING" value="LEADS Smart Scheduler"/>
	<entry key="description" type="STRING" value="Scheduling query trees on multiple microclouds"/>
	<entry key="image" type="STRING" value="SmartGrid.png"/>
	<entry key="tags" type="STRING" value="SmartGrid TAG"/>
  </config>
  <properties>
  		<propentry key="numberOfClouds" type="INT" value="3"/>
  		<propentry key="numberOfClientsperCloud" type="INT" value="10"/>
  		<propentry key="numberofQueriesperClient" type="INT" value="100" />
   		<propentry key="webpagesRatio" type="INT" value="60"/>
  		<propentry key="useRandomScheduler" type="INT" value="0"/>
  		<propentry key="log" type="INT" value="0"/>
  		<propentry key="inputSizeGB" type="INT" value="29"/>
  </properties>
  <requirements>
    <reqentry key="inputnumber" type="INT" value="3"/>
    <reqentry key="outputnumber" type="INT" value="1"/>
    <reqentry key="minimumCandidates" type="INT" value="1"/>
    <reqentry key="maximumCandidates" type="INT" value="1"/>
  </requirements>
</icomponent>
